server:
    port: 8080
    context-path: /api
spring:
    devtools:
      restart:
        exclude:  static/**,public/**
        enabled:  true
    datasource:
        name: sv
        url: jdbc:mysql://115.29.32.62:3306/zwd?useUnicode=true&characterEncoding=utf8
        username: root
        password: 7d428bc667
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml